# Generated by Django 3.0.8 on 2021-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='dept',
            field=models.CharField(choices=[('it', 'information technology'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication')], default='cse', max_length=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('4-2', '4-2')], default='3-1', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
