# Generated by Django 4.2.1 on 2023-06-30 08:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210125_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_etime',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_stime',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default='Assistant Professor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='none', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='d',
            field=models.CharField(choices=[('it', 'information technology'), ('eee', 'electrical'), ('cse', 'computer science'), ('ece', 'electronics and communication'), ('mca', 'master of computer application')], default='CSE', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
