# Generated by Django 4.2.1 on 2023-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_exam_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduct',
            name='fna3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
